name: CI - Testes Automáticos

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar o projeto
        run: javac -d out $(find . -name "*.java")

      - name: Rodar testes
        run: |
          java -cp out org.junit.platform.console.ConsoleLauncher --scan-classpath
